linters-settings:
  errcheck:
    ignore: github.com/go-kit/kit/log:.*

linters:
  fast: false
  presets:
    - style
    - bugs
    - unused
    - format
  disable:
    - interfacer
    - gomnd
    - godox
    - funlen
    - exhaustivestruct
    - gochecknoglobals
    - gochecknoinits
    - forbidigo
